### ISSUE TITLE
#US17-Como usuario, quiero tener una vista, para poder agregar mi medidor o medidores

### ISSUE THREAD

**Issue by Frangia22** [cgavernet/ISPCFullSatckProject#127]
- [ ] Quiero un formulario para agregar un medidor
- [ ] Quiero un vista para editar el medidor o eliminarlo

**Comment by danielpozzo** [comment]
Actualización del proceso de gestión y documentación en GitHub.

**Comment by cgavernet** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [testgit](https://trello.com/c/ufTRKN5B/1-testgit)
