### ISSUE TITLE
#TK15 - Agregar Responsividad al Sitio

### ISSUE THREAD

**Issue by cgavernet** [cgavernet/ISPCFullSatckProject#28]
- [ ] Aplicar la responsividad al sitio Web
- [x] Testear en diferentes dispositivos

**Comment by DiegolPl** [comment]
Agregado la responsividad en vistas de home y notificaciones (alertas)

**Comment by Julimartins** [comment]
Agregada la responsividad del Login y de la pantalla de reestablecer contraseña.
Testeada en tamaño celular, tablet y computadora de escritorio.
