### ISSUE TITLE
#TK20 - Agregar Validaciones a Formularios con JS

### ISSUE THREAD

**Issue by cgavernet** [cgavernet/ISPCFullSatckProject#33]
Funcionalidad con JavaScript en formularios. Validar por tipos de inputs (text, number, email, date, select, segun lo que se requiera), agregar maxlenght y minlenght en los campos nombres, apellido, si solicitan DNI, usar MIN=1000000 MAX=99999999, por ejemplo.

**Comment by DiegolPl** [comment]
Agregado la funcionalidad con javascript en vistas home y notificaciones (alertas)

**Comment by danielpozzo** [comment]
Buenos días, ya agregué funcionalidades con JavaScript en la vista "Inicio".
Realicé funcionalidades de estilo con JS y de validación del formulario de contacto.

**Comment by danielpozzo** [comment]
Aclaración, en el caso del formulario de contacto de la página "Inicio" utilicé expresiones regulares para validar los campos nombre y mensage donde valido la cantidad mínima y máxima de caracteres que los usuarios pueden ingresar...

**Comment by Julimartins** [comment]
Agrego validación con JS a patalla Login para usuario y contraseña. También sumé animación con JS para deslizar hacia la pantalla de reestablecer contraseña.
