### ISSUE TITLE
#TK21 - Reparar enlaces marcadores en pagina inicio.html

### ISSUE THREAD

**Issue by cgavernet** [cgavernet/ISPCFullSatckProject#35]
- [x] Página de inicio crear los enlaces a las secciones

**Comment by danielpozzo** [comment]
Hola equipo, ya generé los enlaces del menú de la página "Inicio" según el siguiente detalle:
-> Renombré **INICIO** por **ADMINISTRADOR** -> Enlace a la página **loginAdmin.html**.
-> Enlacé la opción de menú **SERVICIOS** a la sección homónima.
-> Enlacé la opción de menú **FAQ** a la sección homónima.
-> Enlacé la opción de menú **CONTACTO** a la sección homónima.
