### ISSUE TITLE
#US01 - Como administrador, quiero poder ver el número total de usuarios registrados en el sitio web.

### ISSUE THREAD

**Issue by cgavernet** [cgavernet/ISPCFullSatckProject#42]
- [ ] Agregar una sección de estadísticas de usuarios registrados en el panel de administrador.
- [ ] Crear una consulta SQL para obtener el número total de usuarios registrados.
- [ ] Escribir código para mostrar el número total de usuarios registrados en la sección de estadísticas.

**Comment by danielpozzo** [comment]
Documentación de #US01
