### ISSUE TITLE
#US4 - Como usuario, quiero que la web cuente con una seccion de planes o suscripciones para poder escoger el que se adapte a las necesidades requeridas

### ISSUE THREAD

**Issue by Frangia22** [cgavernet/ISPCFullSatckProject#45]
- [x] Definir distintos planes con distintos limites, para que el cliente pueda elegir el que mejor se le adapte
- [x] Diseñar template para los planes ofrecidos

**Comment by danielpozzo** [comment]
Documentación de #56
