### ISSUE TITLE
#US2-Como administrador, quiero poder agregar nuevos productos al sitio web, incluyendo detalles como el tipo de producto, el precio, la descripción y la cantidad disponible.

### ISSUE THREAD

**Issue by Frangia22** [cgavernet/ISPCFullSatckProject#46]
- [ ] Agregar un formulario de creación de producto en el panel de administración.
- [ ] Escribir código para validar los datos ingresados por el administrador en el formulario de creación de producto.
- [ ] Escribir código para agregar el producto a la base de datos una vez que se hayan validado los datos.

**Comment by cgavernet** [comment]
- [ ] Agregar un formulario de creación de producto en el panel de administración.
- [ ] Escribir código para validar los datos ingresados por el administrador en el formulario de creación de producto.
- [ ] Escribir código para agregar el producto a la base de datos una vez que se hayan validado los datos.

**Comment by danielpozzo** [comment]
Documentación de #US2
