### ISSUE TITLE
#US5-Como administrador, quiero poder actualizar la información del producto existente en el sitio web, incluyendo detalles como el precio, la descripción y la cantidad disponible.

### ISSUE THREAD

**Issue by Frangia22** [cgavernet/ISPCFullSatckProject#47]
- [ ] Agregar un formulario de actualización de producto en el panel de administración.
- [ ] Escribir código para recuperar los datos actuales del producto de la base de datos.
- [ ] Escribir código para validar los datos ingresados por el administrador en el formulario de actualización de producto. 
- [ ] Escribir código para actualizar el producto en la base de datos una vez que se hayan validado los datos.

**Comment by danielpozzo** [comment]
Documentación de #US5
