### ISSUE TITLE
#US6-Como administrador, quiero poder eliminar productos del sitio web que ya no estén disponibles o que ya no sean relevantes para el negocio.

### ISSUE THREAD

**Issue by Frangia22** [cgavernet/ISPCFullSatckProject#48]
- [ ] Agregar una opción de eliminación de producto en el panel de administración.
- [ ] Escribir código para recuperar los datos del producto a eliminar de la base de datos. 
- [ ] Escribir código para confirmar que el administrador realmente desea eliminar el producto.
- [ ] Escribir código para eliminar el producto de la base de datos.

**Comment by danielpozzo** [comment]
Documentación de #US6
