### ISSUE TITLE
#TK04 - Registrar la Especificación de Requerimientos mediante la documentación IEEE830 

### ISSUE THREAD

**Issue by cgavernet** [cgavernet/ISPCFullSatckProject#5]
Subirlo en una carpeta de GitHub en la rama main

**Comment by Frangia22** [comment]
Drive con documento IEEE830 para adaptarlo a nuestro proyecto.
https://docs.google.com/document/d/1HdfV1eNDtGvoceyE2F7hfiwcwsObhwbCBqc6Rl-3NEI/edit?usp=sharing

**Comment by DiegolPl** [comment]
Modifiqué con lo que tenía en mi borrador para complementar al borrador subido en dicho link
