### ISSUE TITLE
#US14-Como cliente, quiero poder realizar el pago de mi compra, para recibir los productos o servicios adquiridos.

### ISSUE THREAD

**Issue by Frangia22** [cgavernet/ISPCFullSatckProject#56]
- [ ] Agregar una sección de pago en la página de pago.
- [ ] Integrar una pasarela de pago para procesar el pago del cliente.
- [ ] Escribir código para registrar el pago y completar la compra.

**Comment by danielpozzo** [comment]
Documentación de #US14
