### ISSUE TITLE
#US16 - Como propietario quiero que mi página web de AnalizAr sea una aplicación de página única para que el cliente tenga una experiencia más fluida y moderna.

### ISSUE THREAD

**Issue by Frangia22** [cgavernet/ISPCFullSatckProject#58]
- [x] Analizar la aplicación anterior y diagramar las vistas y componentes.
- [x] Transformar la aplicación en una SPA.
- [x] crear vistas y componentes.

**Comment by danielpozzo** [comment]
Documentación de #US16
