### ISSUE TITLE
#TK07 - Idea de mapa del Sitio

### ISSUE THREAD

**Issue by cgavernet** [cgavernet/ISPCFullSatckProject#8]
## Mapa de sitio Analizar

![Image](https://user-images.githubusercontent.com/56803807/194678818-884797fc-3d6a-4223-96e0-87f196bdb572.png)

**Comment by Frangia22** [comment]
<img width="1280" alt="Analizar - Mapa de sitio" src="https://user-images.githubusercontent.com/56803807/193435229-1797d336-80a3-43e7-bad9-1858c6d7b540.png">
<img width="2213" alt="Analizar - Mapa de sitio2" src="https://user-images.githubusercontent.com/56803807/193435228-18d32c02-e8c5-4c6b-b9fe-f1094f520e4a.png">

**Comment by cgavernet** [comment]
Excelente trabajo, se basa en el borrador, está bien claro el mapa del sitio y las paginas.
